name: Deploy Firebase App

on:
  push:
    branches:
      - main  # Déploiement automatique à chaque push sur main

permissions:
  contents: write  # Autoriser l'écriture sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Évite les problèmes de branches orphelines

      - name: Create Firebase Config JSON
        run: |
          echo '{
            "apiKey": "${{ secrets.FIREBASE_API_KEY }}",
            "authDomain": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            "projectId": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "storageBucket": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "messagingSenderId": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "appId": "${{ secrets.FIREBASE_APP_ID }}"
          }' > firebase-config.json

      - name: Commit and Push Config File
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add firebase-config.json
          git commit -m "🔒 Add Firebase config (Auto-generated by GitHub Actions)" || echo "No changes to commit"
          git push origin main
